### ISSUE TITLE
Documentation for current functionality

### ISSUE THREAD

**Issue by furzeface** [tawashley/whisp#4]

**Comment by tawashley** [comment]
dirReader functions have been updated with JS doc blocks

**Comment by tawashley** [comment]
Remaining module functions JS doc'ed.

**Comment by furzeface** [comment]
@tawashley 

```sh
git checkout feature/docs && npm i && grunt docs && open -a /Applications/Google\ Chrome.app docs/index.html
```

**Comment by furzeface** [comment]
To document:
- [ ] `lib/config.js`
- [ ] `lib/dirReader.js`
- [x] `lib/utils.js`
- [x] `lib/generator.js`
- [x] `lib/whisp.js`

**Comment by furzeface** [comment]
Going to merge this into develop if you're happy with the result of the above command :question:
